//
//  QuestionService.swift
//  WizardCahill
//
//  Created by Karen Seimears on 3/29/24.
//

import Foundation

class LearnService: ObservableObject {
    
    var learnBank = [Learn]()
    
    init() {
        loadLearns()
    }
    
    func loadLearns() {
        
        learnBank.append(Learn(title: "iPad Basics", subtitle: "Apps", explore: "Learn about managing your apps on the iPad here.", exploreURL: "https://support.appl.com/guide/ipad/move-apps-and-widgets-on-the-home-screen-ipadf6ea1ce5/ipados", dos: ["Put the apps you use the most in your dock.", "Make a folder of similar apps.", "Rename your folder to represent those apps.", "Go to Self-Service and install an app you don’t have."], extends: ["Can you switch between apps using a gesture?", "Can you force close an app that isn’t working?"], topic: .ipad))
        
        learnBank.append(Learn(title: "iPad Basics", subtitle: "Control Center", explore: "Learn about editing and using the Control Center.", exploreURL:  "https://support.apple.com/guide/ipad/use-and-customize-control-center-ipade572ca56/17.0/ipados/17.0", dos: ["Customize your CC to include screen recording.", "Remove CC features you don't use.", "Add a timer to your CC.", "Create a screen recording with your mic on."], extends: ["Show a teacher how to customize CC.", "Connect to an Apple TV (with permission)."], topic: .ipad))
        
        learnBank.append(Learn(title: "iPad Basics", subtitle: "Camera", explore: "Learn about using your iPad's camera.", exploreURL:  "https://support.apple.com/guide/ipad/take-photos-ipad99b53a71/17.0/ipados/17.0", dos: ["Take a screen shot.", "Shoot a slo-mo & timelapse video. Notice the differences.", "Photograph something with text and copy the text to Notes.", "Lock your auto focuse and auto exposure."], extends: ["Add the grid to your camera.", "Explore the differences in live modes."], topic: .ipad))
        
        learnBank.append(Learn(title: "iPad Basics", subtitle: "Spoken Content", explore: "Learn about managing your apps on the iPad here.", exploreURL:  "https://www.stackoverflow.com", dos: ["Put the apps you use the most in your dock.", "Make a folder of similar apps.", "Rename your folder to represent those apps.", "Go to Self-Service and install an app you don’t have."], extends: ["Can you switch between apps using a gesture?", "Can you force close an app that isn’t working?"], topic: .ipad))
        
        learnBank.append(Learn(title: "iPad Basics", subtitle: "Notes", explore: "Learn about the Notes app here.", exploreURL:  "https://www.stackoverflow.com", dos: ["Start a new note.", "Add a drawing to your note.", "Explore the other elements you can add to notes.", "Under share, change the background to graph paper."], extends: ["Can you airdrop a note?", "Can you organize notes into folders?"], topic: .ipad))
        
        learnBank.append(Learn(title: "iPad Basics", subtitle: "Translate", explore: "Learn about the Translate app here.", exploreURL:  "https://www.stackoverflow.com", dos: ["Explore having a conversation using the app.", "Try the different ways including typing, talking and face to face.", "Take a photo of text and translate it."], extends: ["Find a friend and have a conversation in two languages.", "Select text in Pages or Keynote, highlight the text and use translate from the options."], topic: .ipad))
        
        learnBank.append(Learn(title: "Troubleshooting", subtitle: "Basics", explore: "Learn about managing your apps on the iPad here.", exploreURL:  "https://www.stackoverflow.com", dos: ["Put the apps you use the most in your dock.", "Make a folder of similar apps.", "Rename your folder to represent those apps.", "Go to Self-Service and install an app you don’t have."], extends: ["Can you switch between apps using a gesture?", "Can you force close an app that isn’t working?"], topic: .troubleshooting))
        
        learnBank.append(Learn(title: "Troubleshooting", subtitle: "iCloud", explore: "Learn about managing your apps on the iPad here.", exploreURL:  "https://www.stackoverflow.com", dos: ["Put the apps you use the most in your dock.", "Make a folder of similar apps.", "Rename your folder to represent those apps.", "Go to Self-Service and install an app you don’t have."], extends: ["Can you switch between apps using a gesture?", "Can you force close an app that isn’t working?"], topic: .troubleshooting))
        
        learnBank.append(Learn(title: "Troubleshooting", subtitle: "Wifi", explore: "Learn about managing your apps on the iPad here.", exploreURL:  "https://www.stackoverflow.com", dos: ["Put the apps you use the most in your dock.", "Make a folder of similar apps.", "Rename your folder to represent those apps.", "Go to Self-Service and install an app you don’t have."], extends: ["Can you switch between apps using a gesture?", "Can you force close an app that isn’t working?"], topic: .troubleshooting))
        
        learnBank.append(Learn(title: "Troubleshooting", subtitle: "Self-Service", explore: "Learn about managing your apps on the iPad here.", exploreURL:  "https://www.stackoverflow.com", dos: ["Put the apps you use the most in your dock.", "Make a folder of similar apps.", "Rename your folder to represent those apps.", "Go to Self-Service and install an app you don’t have."], extends: ["Can you switch between apps using a gesture?", "Can you force close an app that isn’t working?"], topic: .troubleshooting))
        
        learnBank.append(Learn(title: "Troubleshooting", subtitle: "Updates", explore: "Learn about managing your apps on the iPad here.", exploreURL:  "https://www.stackoverflow.com", dos: ["Put the apps you use the most in your dock.", "Make a folder of similar apps.", "Rename your folder to represent those apps.", "Go to Self-Service and install an app you don’t have."], extends: ["Can you switch between apps using a gesture?", "Can you force close an app that isn’t working?"], topic: .troubleshooting))
        
        learnBank.append(Learn(title: "Troubleshooting", subtitle: "Drive", explore: "Learn about managing your apps on the iPad here.", exploreURL:  "https://www.stackoverflow.com", dos: ["Put the apps you use the most in your dock.", "Make a folder of similar apps.", "Rename your folder to represent those apps.", "Go to Self-Service and install an app you don’t have."], extends: ["Can you switch between apps using a gesture?", "Can you force close an app that isn’t working?"], topic: .troubleshooting))
        
        learnBank.append(Learn(title: "Video Production", subtitle: "Photos", explore: "Learn about managing your apps on the iPad here.", exploreURL:  "https://www.stackoverflow.com", dos: ["Put the apps you use the most in your dock.", "Make a folder of similar apps.", "Rename your folder to represent those apps.", "Go to Self-Service and install an app you don’t have."], extends: ["Can you switch between apps using a gesture?", "Can you force close an app that isn’t working?"], topic: .videoProd))
        
        learnBank.append(Learn(title: "Video Production", subtitle: "Clips Video", explore: "Learn about managing your apps on the iPad here.", exploreURL:  "https://www.stackoverflow.com", dos: ["Put the apps you use the most in your dock.", "Make a folder of similar apps.", "Rename your folder to represent those apps.", "Go to Self-Service and install an app you don’t have."], extends: ["Can you switch between apps using a gesture?", "Can you force close an app that isn’t working?"], topic: .videoProd))
        
        learnBank.append(Learn(title: "Video Production", subtitle: "Clips Live Titles", explore: "Learn about managing your apps on the iPad here.", exploreURL:  "https://www.stackoverflow.com", dos: ["Put the apps you use the most in your dock.", "Make a folder of similar apps.", "Rename your folder to represent those apps.", "Go to Self-Service and install an app you don’t have."], extends: ["Can you switch between apps using a gesture?", "Can you force close an app that isn’t working?"], topic: .videoProd))
        
        learnBank.append(Learn(title: "Video Production", subtitle: "iMovie", explore: "Learn about managing your apps on the iPad here.", exploreURL:  "https://www.stackoverflow.com", dos: ["Put the apps you use the most in your dock.", "Make a folder of similar apps.", "Rename your folder to represent those apps.", "Go to Self-Service and install an app you don’t have."], extends: ["Can you switch between apps using a gesture?", "Can you force close an app that isn’t working?"], topic: .videoProd))
        
        learnBank.append(Learn(title: "Video Production", subtitle: "Green Screen", explore: "Learn about managing your apps on the iPad here.", exploreURL:  "https://www.stackoverflow.com", dos: ["Put the apps you use the most in your dock.", "Make a folder of similar apps.", "Rename your folder to represent those apps.", "Go to Self-Service and install an app you don’t have."], extends: ["Can you switch between apps using a gesture?", "Can you force close an app that isn’t working?"], topic: .videoProd))
        
        learnBank.append(Learn(title: "Pages", subtitle: "Pages Basics", explore: "Learn about managing your apps on the iPad here.", exploreURL:  "https://www.stackoverflow.com", dos: ["Put the apps you use the most in your dock.", "Make a folder of similar apps.", "Rename your folder to represent those apps.", "Go to Self-Service and install an app you don’t have."], extends: ["Can you switch between apps using a gesture?", "Can you force close an app that isn’t working?"], topic: .pages))
        
        learnBank.append(Learn(title: "Pages", subtitle: "Documents", explore: "Learn about managing your apps on the iPad here.", exploreURL:  "https://www.stackoverflow.com", dos: ["Put the apps you use the most in your dock.", "Make a folder of similar apps.", "Rename your folder to represent those apps.", "Go to Self-Service and install an app you don’t have."], extends: ["Can you switch between apps using a gesture?", "Can you force close an app that isn’t working?"], topic: .pages))
        
        learnBank.append(Learn(title: "Pages", subtitle: "Media", explore: "Learn about managing your apps on the iPad here.", exploreURL:  "https://www.stackoverflow.com", dos: ["Put the apps you use the most in your dock.", "Make a folder of similar apps.", "Rename your folder to represent those apps.", "Go to Self-Service and install an app you don’t have."], extends: ["Can you switch between apps using a gesture?", "Can you force close an app that isn’t working?"], topic: .pages))
        
        learnBank.append(Learn(title: "Pages", subtitle: "eBooks", explore: "Learn about managing your apps on the iPad here.", exploreURL:  "https://www.stackoverflow.com", dos: ["Put the apps you use the most in your dock.", "Make a folder of similar apps.", "Rename your folder to represent those apps.", "Go to Self-Service and install an app you don’t have."], extends: ["Can you switch between apps using a gesture?", "Can you force close an app that isn’t working?"], topic: .pages))
        
        learnBank.append(Learn(title: "Pages", subtitle: "Formatting", explore: "Learn about managing your apps on the iPad here.", exploreURL:  "https://www.stackoverflow.com", dos: ["Put the apps you use the most in your dock.", "Make a folder of similar apps.", "Rename your folder to represent those apps.", "Go to Self-Service and install an app you don’t have."], extends: ["Can you switch between apps using a gesture?", "Can you force close an app that isn’t working?"], topic: .pages))
        
        learnBank.append(Learn(title: "Pages", subtitle: "Collaborating", explore: "Learn about managing your apps on the iPad here.", exploreURL:  "https://www.stackoverflow.com", dos: ["Put the apps you use the most in your dock.", "Make a folder of similar apps.", "Rename your folder to represent those apps.", "Go to Self-Service and install an app you don’t have."], extends: ["Can you switch between apps using a gesture?", "Can you force close an app that isn’t working?"], topic: .pages))
        
        learnBank.append(Learn(title: "Keynote", subtitle: "Keynote Basics", explore: "Learn about managing your apps on the iPad here.", exploreURL:  "https://www.stackoverflow.com", dos: ["Put the apps you use the most in your dock.", "Make a folder of similar apps.", "Rename your folder to represent those apps.", "Go to Self-Service and install an app you don’t have."], extends: ["Can you switch between apps using a gesture?", "Can you force close an app that isn’t working?"], topic: .keynote))
        
        learnBank.append(Learn(title: "Keynote", subtitle: "Slides", explore: "Learn about managing your apps on the iPad here.", exploreURL:  "https://www.stackoverflow.com", dos: ["Put the apps you use the most in your dock.", "Make a folder of similar apps.", "Rename your folder to represent those apps.", "Go to Self-Service and install an app you don’t have."], extends: ["Can you switch between apps using a gesture?", "Can you force close an app that isn’t working?"], topic: .keynote))
        
        learnBank.append(Learn(title: "Keynote", subtitle: "Movies", explore: "Learn about managing your apps on the iPad here.", exploreURL:  "https://www.stackoverflow.com", dos: ["Put the apps you use the most in your dock.", "Make a folder of similar apps.", "Rename your folder to represent those apps.", "Go to Self-Service and install an app you don’t have."], extends: ["Can you switch between apps using a gesture?", "Can you force close an app that isn’t working?"], topic: .keynote))
        
        learnBank.append(Learn(title: "Keynote", subtitle: "Audio", explore: "Learn about managing your apps on the iPad here.", exploreURL:  "https://www.stackoverflow.com", dos: ["Put the apps you use the most in your dock.", "Make a folder of similar apps.", "Rename your folder to represent those apps.", "Go to Self-Service and install an app you don’t have."], extends: ["Can you switch between apps using a gesture?", "Can you force close an app that isn’t working?"], topic: .keynote))
        
        learnBank.append(Learn(title: "Keynote", subtitle: "GIFs", explore: "Learn about managing your apps on the iPad here.", exploreURL:  "https://www.stackoverflow.com", dos: ["Put the apps you use the most in your dock.", "Make a folder of similar apps.", "Rename your folder to represent those apps.", "Go to Self-Service and install an app you don’t have."], extends: ["Can you switch between apps using a gesture?", "Can you force close an app that isn’t working?"], topic: .keynote))
        
        learnBank.append(Learn(title: "Keynote", subtitle: "Collaborating", explore: "Learn about managing your apps on the iPad here.", exploreURL:  "https://www.stackoverflow.com", dos: ["Put the apps you use the most in your dock.", "Make a folder of similar apps.", "Rename your folder to represent those apps.", "Go to Self-Service and install an app you don’t have."], extends: ["Can you switch between apps using a gesture?", "Can you force close an app that isn’t working?"], topic: .keynote))
        
        learnBank.append(Learn(title: "Numbers", subtitle: "Numbers Basics", explore: "Learn about managing your apps on the iPad here.", exploreURL:  "https://www.stackoverflow.com", dos: ["Put the apps you use the most in your dock.", "Make a folder of similar apps.", "Rename your folder to represent those apps.", "Go to Self-Service and install an app you don’t have."], extends: ["Can you switch between apps using a gesture?", "Can you force close an app that isn’t working?"], topic: .keynote))
        
        learnBank.append(Learn(title: "Numbers", subtitle: "Media", explore: "Learn about managing your apps on the iPad here.", exploreURL:  "https://www.stackoverflow.com", dos: ["Put the apps you use the most in your dock.", "Make a folder of similar apps.", "Rename your folder to represent those apps.", "Go to Self-Service and install an app you don’t have."], extends: ["Can you switch between apps using a gesture?", "Can you force close an app that isn’t working?"], topic: .keynote))
        
        learnBank.append(Learn(title: "Numbers", subtitle: "Charts", explore: "Learn about managing your apps on the iPad here.", exploreURL:  "https://www.stackoverflow.com", dos: ["Put the apps you use the most in your dock.", "Make a folder of similar apps.", "Rename your folder to represent those apps.", "Go to Self-Service and install an app you don’t have."], extends: ["Can you switch between apps using a gesture?", "Can you force close an app that isn’t working?"], topic: .keynote))
        
        learnBank.append(Learn(title: "Numbers", subtitle: "Tables", explore: "Learn about managing your apps on the iPad here.", exploreURL:  "https://www.stackoverflow.com", dos: ["Put the apps you use the most in your dock.", "Make a folder of similar apps.", "Rename your folder to represent those apps.", "Go to Self-Service and install an app you don’t have."], extends: ["Can you switch between apps using a gesture?", "Can you force close an app that isn’t working?"], topic: .numbers))
        
        learnBank.append(Learn(title: "Numbers", subtitle: "Drawing", explore: "Learn about managing your apps on the iPad here.", exploreURL:  "https://www.stackoverflow.com", dos: ["Put the apps you use the most in your dock.", "Make a folder of similar apps.", "Rename your folder to represent those apps.", "Go to Self-Service and install an app you don’t have."], extends: ["Can you switch between apps using a gesture?", "Can you force close an app that isn’t working?"], topic: .numbers))
        
        learnBank.append(Learn(title: "Numbers", subtitle: "Collaboration", explore: "Learn about managing your apps on the iPad here.", exploreURL:  "https://www.stackoverflow.com", dos: ["Put the apps you use the most in your dock.", "Make a folder of similar apps.", "Rename your folder to represent those apps.", "Go to Self-Service and install an app you don’t have."], extends: ["Can you switch between apps using a gesture?", "Can you force close an app that isn’t working?"], topic: .numbers))
    }
}
                        
